-- Drop existing tables to start fresh
DROP TABLE IF EXISTS recommendation;
DROP TABLE IF EXISTS user_product_recommendation;

-- New table for top recommendations
CREATE TABLE recommendation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skin_type VARCHAR(255),
    concern VARCHAR(255),
    recommendations VARCHAR(255)
);

-- Table for community-submitted recommendations
CREATE TABLE user_product_recommendation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skin_type VARCHAR(255),
    concerns VARCHAR(255),
    product_type VARCHAR(255),
    brand_name VARCHAR(255),
    product_name VARCHAR(255)
);